name: Building image frontend-tickitz-react and pushing to GHCR

on: [push]

jobs:
  Build-And-Publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        run: docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image (frontend)
        run: docker build -f Dockerfile.frontend -t ghcr.io/darari17/frontend:latest .

      - name: Push Docker image (frontend)
        run: docker push ghcr.io/darari17/frontend:latest
